"""
POC4 explanation layer — Vans / VF DotIQ.

POC1-3 built a fully deterministic pipeline: rules decide what counts as a
situation, and a confidence score decides how much to trust it. Nothing in
this file changes that. POC4 adds a layer ON TOP that takes a situation
DotIQ has already decided is real, and turns its evidence into something a
stocker or merchandiser can read in ten seconds — the LLM explains, it does
not decide.

How this actually runs:
  - build_evidence_pack() turns one insight from ranked_insights.json into a
    compact, structured JSON object — only real numbers already computed by
    the deterministic engine, nothing invented.
  - build_prompt() turns that evidence pack into the exact prompt that would
    be sent to Claude.
  - explain() calls the real Anthropic API if ANTHROPIC_API_KEY is set in
    the environment (pip install anthropic; see PROMPT below for the exact
    request). If no key is present — the case in this sandbox — it reads
    the matching entry from cached_explanations.json instead: those entries
    were generated by Claude from this exact evidence, once, for this demo
    dataset. Same input shape either way; only the source of the text
    differs. Swapping in a real key requires no other code change.

Run with `python3 explain.py` after detect_and_correlate.py has produced
ranked_insights.json.
"""
import json
import os

MODEL = "claude-sonnet-4-5"

SYSTEM_PROMPT = (
    "You are DotIQ's explanation layer for Vans/VF. You are given a situation "
    "that a deterministic rules engine has already detected and scored — you do "
    "not decide whether it's real or how confident to be, that's fixed upstream. "
    "Your only job: turn the evidence into something a store operations person "
    "can read in ten seconds. Write in plain, natural language — no corporate "
    "buzzwords, no hedging filler, no restating the JSON. Ground every claim in "
    "a number from the evidence pack; never invent a figure that isn't there. "
    "Return strict JSON with exactly these keys: narrative (2-3 sentences), "
    "key_evidence (3-4 short bullet strings, each citing a specific number), "
    "confidence_rationale (1 sentence, plain language, referencing what drove "
    "the score), suggested_talking_point (1 sentence, the actual thing a "
    "stocker or merchandiser would say to a colleague)."
)


def load_ranked():
    with open("ranked_insights.json") as f:
        return json.load(f)


def build_evidence_pack(insight):
    """Only numbers the deterministic engine already computed — nothing added."""
    pack = {
        "situation_type": insight["situation_type"],
        "product": insight["product"],
        "region": insight["region"],
        "week_start": insight["week_start"],
        "week_end": insight["week_end"],
        "confidence": insight["confidence"],
        "signals": insight["signals"],
        "recommendation_action": insight["recommendation"]["action"],
    }
    if "dealers" in insight["recommendation"]:
        pack["dealers"] = insight["recommendation"]["dealers"]
    if insight.get("promo_influenced"):
        pack["promo_influenced"] = True
        pack["raw_confidence_before_promo_discount"] = insight["raw_confidence"]
        pack["promo_share_pct"] = insight["promo_share_pct"]
    return pack


def build_prompt(evidence_pack):
    return (
        f"Evidence pack (all numbers from the deterministic engine, 10-week window):\n"
        f"{json.dumps(evidence_pack, indent=2)}\n\n"
        f"Write the explanation as specified in the system prompt. Return JSON only."
    )


def call_anthropic_api(evidence_pack):
    """The live path. Requires `pip install anthropic` and ANTHROPIC_API_KEY set."""
    import anthropic
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
    resp = client.messages.create(
        model=MODEL,
        max_tokens=500,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": build_prompt(evidence_pack)}],
    )
    text = resp.content[0].text
    return json.loads(text)


def call_cached(scenario):
    with open("cached_explanations.json") as f:
        cache = json.load(f)
    if scenario not in cache:
        raise KeyError(f"No cached explanation for scenario '{scenario}' — add one or set ANTHROPIC_API_KEY.")
    return {k: v for k, v in cache[scenario].items()}


def explain(insight):
    evidence_pack = build_evidence_pack(insight)
    if os.environ.get("ANTHROPIC_API_KEY"):
        source = "live_api"
        explanation = call_anthropic_api(evidence_pack)
    else:
        source = "cached_demo"
        explanation = call_cached(insight["scenario"])
    return {
        **insight,
        "ai_explanation": explanation,
        "ai_explanation_source": source,
        "evidence_pack_sent_to_llm": evidence_pack,
    }


def main():
    ranked = load_ranked()
    mode_note = (
        "Live mode: ANTHROPIC_API_KEY found — calling the Anthropic API for each explanation."
        if os.environ.get("ANTHROPIC_API_KEY") else
        "Demo mode: no ANTHROPIC_API_KEY in this environment — using cached_explanations.json "
        "(pre-generated by Claude from this exact evidence). Set the key and rerun to call the "
        "live API instead; no other code changes needed."
    )
    print(mode_note)

    explained_top5 = [explain(i) for i in ranked["top5"]]
    explained_cut = [explain(i) for i in ranked["cut"]]

    out = {
        "mode": "live_api" if os.environ.get("ANTHROPIC_API_KEY") else "cached_demo",
        "mode_note": mode_note,
        "model": MODEL,
        "system_prompt": SYSTEM_PROMPT,
        "top_n": ranked["top_n"],
        "top5": explained_top5,
        "cut": explained_cut,
    }
    with open("explained_insights.json", "w") as f:
        json.dump(out, f, indent=2)

    print(f"\nExplained {len(explained_top5)} top-ranked situations and {len(explained_cut)} cut situation(s).")
    print("Wrote explained_insights.json")


if __name__ == "__main__":
    main()
